### ISSUE TITLE
[Request] Additional sorting/filter options

### ISSUE THREAD

**Issue by TheCzar1994** [beatmaps-io/beatsaver-main#105]
Would be nice to be able to sort or filter by more than one factor. For example, if I want to see verified mappers, I can easily toggle the verified mappers filter. If I want to see curated maps, same thing. But what if I want to see all verified mappers and curated together? Currently can't as far as I know. I'd like to see either the ability to do multi-filters together independent of each other, as well as perhaps what is currently implemented which is the multi-filters together. See my post in the Discord server for additional: https://discord.com/channels/882730837974609940/882730837974609943/967225618196492318

**Comment by helencarnate** [comment]
@TheCzar1994 How much of this issue has since been addressed by the new multi-filtering option for tags? It sounds like what you're requesting on curated and verified is an "OR" operator. This link: https://beatsaver.com/?curated=true&verified=true will return all maps that are **curated** and uploaded by a **verified mapper** but it sounds like you want to be able to see all maps that are curated OR from a verified mapper.

**Comment by TheCzar1994** [comment]
@helencarnate Yeah, the multi-filtering works great for tags, but I'd like to see the "OR" operator added to the general tabs. That way you can filter out non-verified mappers posts while still seeing verified mappers posts that may not get curated.
