### ISSUE TITLE
[Bug] Some maps have a very long (incorrect) song length

### ISSUE THREAD

**Issue by kinsi55** [beatmaps-io/beatsaver-main#132]
Examples:

https://beatsaver.com/maps/26d6e
https://beatsaver.com/maps/26d81
https://beatsaver.com/maps/24781

**Comment by Top-Cat** [comment]
Fixed by beatmaps-io/beatsaver-common-mp@06b3dbe

**Comment by kinsi55** [comment]
Seems like this still happens for some maps: https://beatsaver.com/maps/27f35

**Comment by Top-Cat** [comment]
I'm hoping that just slipped through the cracks of this being released
